### ISSUE TITLE
Problem with code

### ISSUE THREAD

**Issue by hello299** [ethz-asl/COIN-LIO#24]
![2024-10-15 20-33-13 的屏幕截图](https://github.com/user-attachments/assets/bf5347c2-1362-4b68-8be0-14678a9f5596)
Hi,I don't know the purpose of this code segment,i know u_k and v_k is the image coordinate of the points,but i don't know what is the start_idx for and the why the offset is the proj_idx +1 。
Could you give me some advice? thank you!

**Comment by patripfr** [comment]
Hi,
In this part of the code, I create the projection map of the undistorted point cloud (see section III G in the [paper](https://arxiv.org/pdf/2310.01235)).
For the undistorted point cloud, multiple points can project into the same pixel. Therefore, we first store all of them, such that we can later select the one with the shortest range, which happens [here](https://github.com/ethz-asl/COIN-LIO/blob/main/src/projector.cpp#L244-L259).

For each pixel we store a maximum of [`DUPLICATE_POINTS`](https://github.com/ethz-asl/COIN-LIO/blob/main/src/projector.cpp#L7)-1 points, such that we can use a predefined size for vector [`frame.proj_idx`](https://github.com/ethz-asl/COIN-LIO/blob/main/src/projector.cpp#L103) . 
The structure of this vector is as follows: [offset, i_1, i_2, ... , i_9], where offset stores how many points were already projected in this pixel, and i_i stores the index of i-th point that was projected in this pixel.
[`vectorIndexFromRowCol(v_k, u_k)`](https://github.com/ethz-asl/COIN-LIO/blob/main/src/projector.cpp#L95-L97) gives the index in `frame.proj_idx` where the entries for pixel `(v_k, u_k)` start.
`size_t offset = frame.proj_idx[start_idx] + 1;` is because we have to increment the `start_idx` by one since we are adding a point.

**Comment by hello299** [comment]
Ok,thank you very much ,I just text a message in your email provided in the article,please notice it and i share some of my idea in it.
